language: rust
rust:
  - stable
  - beta
  - nightly

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo

services:
  - docker

script:
  - cargo build --verbose --workspace
  - RUST_LOG=info cargo test --verbose --workspace -- --test-threads=1 --nocapture
